### ISSUE TITLE
The specified file extension [js] is invalid

### ISSUE THREAD

**Issue by get-web** [skydiver/october-plugin-forms#214] opened 2020-09-10 11:28 UTC
octobercms build 469

When I turn on the reset form. In the alert window after sending is displayed:
`The specified file extension [js] is invalid." on line 520 of /vendor/october/rain/src/Halcyon/Builder.php`

![inv](https://user-images.githubusercontent.com/39173640/92723038-24a70100-f371-11ea-8a25-d7f1e21b929e.jpg)

**Comment by mjauvin** [comment] 2020-09-10 11:41
duplicate of https://github.com/skydiver/october-plugin-forms/issues/213

**Comment by mjauvin** [comment] 2020-09-11 15:58
Please close this issue.

**Closed** 2020-09-11 18:57 UTC
Labels: bug, duplicate
