### ISSUE TITLE
About the upload feature

### ISSUE THREAD

**Issue by ghost** [skydiver/october-plugin-forms#36] opened 2017-03-02 14:14 UTC
Hello,

About the upload feature, I wonder if you created another component because it's a beta and you will merge it with the standard component when it will be considered as stable, or if it will still be separate component.

I would votre for only one component cause, if you setup a standart form and need to add upload functionnality later, its easier to check "allow upload" on your already existing component that adding and configure from scratch a new one.

**Comment by skydiver** [comment] 2017-03-04 21:50
I've never thought about that but i like the idea.

Still don't know when we can considere files uploads stable ...

**Comment by Alex360hd** [comment] 2017-03-07 15:22
Tested the upload form a little, I encounter weird problem.

It break my html layout, like if there were missing <div>

After some investigation, it seems that the cause of the problem is the code under the _Template for new file_ comment.

It seems that closing divs between scripts tag don't output.

Tested on the latest version of chrome.

Alex

**Comment by Alex360hd** [comment] 2017-03-07 16:08
Its not the fault of your plugin, the cause of the problem was offline responsive image plugin :

More informations here

https://github.com/responsiv/uploader-plugin/issues/17

**Comment by Alex360hd** [comment] 2017-03-08 10:42
Tested the upload feature, (both multiple and single upload), here is my feedback.

Globally, it works well (and I defined my own partial), so I could consider it as stable. Just have some remark/questions :

- Why did you put the submit button in a {{ form_submit() }} twig variables ? I tested to put a standard form submit button and there is no problems.
- The uploader css file can be improved, for example instead of having hardcoded height and negative margin for .responsiv-uploader-fileupload.style-file-single .upload-button, you could use

    position: absolute; height: 100%; right: 0; margin-right: 0;

Personally, now I always use the upload component as it perfectly works even with upload disabled. I just changed the file-upload partial to remove the message that say that the upload option needs to be enabled. I don't see any drawback.

**Comment by Alex360hd** [comment] 2017-03-13 16:26
Here is feedback after more in-depth testing.

Actually, the form upload seems to support only one upload field per form, which can be annoying in some cases (for example a survey where the user need to upload a file in several different places).

I think the plugin should be more flexible by allowing users to embed an upload field where they want (and the number they want).

The phylosophy of this plugin is to automatically detect the different fields, I think it should be the same for upload, by detecting an input type="file"

For single field upload :
    <input type="file" name="img">

For multiple field upload
    <input type="file" name="img" multiple>

Maybe we can add more options like by using data attributes, for example :

    <input type="file" name="img" multiple data-extension=".png, .jpg, .pdf, .zip" data-maxsize="2MB">

The job of the plugin would be to detect the type of the input, and do the magic (it's magic form after all ^^) to make upload works.

It would probably imply a major revamp of the actual system, but it's more inline with the actual plugin phylosophy. Actually it works, but it's too much limited.

**Comment by Zmove** [comment] 2017-03-17 06:40
+1 for the last comment. I had to create a form with multiple upload elements recently and I agree it would be a joy to be able to define an  upload input type exactly like other fields and let the module "magically" do the necessary.

Another suggestion about upload, In the backend, I would prefer to have upload files in the same format as the rest (in the table, with a label in first column and the link in second column) to stay consistent with the rest of the form. In addition, doing like this would keep the order of fields, which is important in my case.

Do you think you can implement the upload feature that way or do I have to think about a fork ?

**Comment by skydiver** [comment] 2017-03-17 12:37
Hello @Zmove 

About the public upload component, a pull request will be much appreciated.

Changes on the backend sounds good to me, will be ready on the next release.

**Comment by skydiver** [comment] 2017-03-20 14:05
@Zmove 

Here is an example of how the attached files will look ![screenshot from 2017-03-20 11 02 08](https://cloud.githubusercontent.com/assets/578784/24103066/de128bea-0d5c-11e7-8115-f7ab716f65ff.png)

The files list needs to go on the bottom, because the order is not stored on the data array.

What do you think?

**Comment by Zmove** [comment] 2017-03-20 14:19
Hello,

It's better than the previous version that displayed the files in buttons outside the table.

About the order of the field, I'm not sure to understand why the upload fields are different than the regular fields that can be ordered ? I think the solution is to detect all the file input type, like the rest of the fields.

I will try to examine the code and see if I can do something, but it will take times as I'm discovering laravel and october CMS at the same time. So I don't understand everything yet.

**Comment by GeRoHi** [comment] 2017-06-27 17:11
Hello,
I encounter the same problem that Alex360hd experienced. 
Template for new file is breaking my html, closing divs not being outputed.
I do have the responsive image plugin, the only solution is to delete it ? 
I don't understand what's happening here, I'm new to october/laravel.

**Comment by Alex360hd** [comment] 2017-06-28 07:16
Hello,

The only solution is to remove the responsive image plugin actually.

This is an (issue related to the responsive image plugin)[https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/issues/13], not magic form

**Comment by GeRoHi** [comment] 2017-06-28 16:45
Ok thank you, this is disapointing that I have to choose between responsive images and magic forms.
Will definitely think about a fork on responsive images, php html parser is a pain, wouldn't it be easier to parse the html as plain text ?

**Comment by Kusdrae** [comment] 2020-12-21 13:12
I'm starting to use the Magic Form Upload, but for some reason, when i put the `{{ form_ajax(__SELF__ ~ '::onFormSubmit') }}
    <div id="{{ __SELF__ }}_forms_flash"></div>
    
    {% partial '@file-upload' %}
    {{ form_submit() }}
{{ form_close() }}`, and i go the my website, and click on the "upload your files", it simply does nothing, doesn't open a browse to select the files, i have no idea how to fix this and would be really glad if someone could help me out!
FYI: i did change the "__SELF__" to my component name

**Comment by Kusdrae** [comment] 2021-01-15 12:29
@skydiver @ghost please help :'(

**Comment by tfprado** [comment] 2021-06-10 14:55
@Kusdrae do you have {% scripts %} and {% framework extras %} in your layout?
I had some issues with my JS load order that caused the same problem with the uploader not triggering the select file windows when clicked, switching the load order fixed it

**Comment by Kusdrae** [comment] 2021-06-11 18:32
@tfprado Dude, i thought i had {% scripts %} and {% framework extras %} in my page, to be honest i gave up trying to fix it, since the form without upload worked just fine, but now that you answered, i went back and try to fix it, and it works!!!!!!!!!!!
thank you so much man!!!!
The only problem is that it is not sending the file as an attachment, but it's recording in the "Records" in October

**Comment by tfprado** [comment] 2021-06-11 18:44
@Kusdrae Make sure you have the option to attach it to the notification selected. 
If you are still not getting the attachment in the email check the mail logs
<img width="426" alt="Screen Shot 2021-06-11 at 2 38 20 PM" src="https://user-images.githubusercontent.com/3441074/121734787-3ca7de80-cac3-11eb-8a54-2c57b3411f75.png">

**Comment by Kusdrae** [comment] 2021-06-11 18:53
@tfprado yes, i have this option selected
![Captura de tela 2021-06-11 155225](https://user-images.githubusercontent.com/58086236/121735829-10915b00-cacd-11eb-9566-67d0b31bdbfd.png)

The error i'm getting is this: 
![Captura de tela 2021-06-11 155310](https://user-images.githubusercontent.com/58086236/121735913-299a0c00-cacd-11eb-91c4-75edee407d46.png)

**Comment by tfprado** [comment] 2021-06-11 18:58
@Kusdrae that's interesting I don't see Input being used anywhere in SendMail.php. What is your plugin version? I am using 1.5.1

**Comment by Kusdrae** [comment] 2021-06-11 19:01
@tfprado i'm using the same version, 1.5.1
i see it in this line:
 /*  $message->attach($file->getLocalPath(), ['as' => $file->getFilename()]);   */ $message->attach( Input::file('attachment') );

**Comment by tfprado** [comment] 2021-06-11 19:04
This is what I have
```php
              // ADD UPLOADS
                if (isset($properties['mail_uploads']) && $properties['mail_uploads'] && !empty($files)) {
                    foreach ($files as $file) {
                        $message->attach($file->getLocalPath(), ['as' => $file->getFilename()]);
                    }
                }
`

**Comment by tfprado** [comment] 2021-06-11 19:06
@Kusdrae and the sendMail
```php
<?php

namespace Martin\Forms\Classes;

use Mail;
use System\Models\MailTemplate;
use Martin\Forms\Classes\BackendHelpers;

class SendMail {

    public static function sendNotification($properties, $post, $record, $files) {
`

**Comment by Kusdrae** [comment] 2021-06-11 19:07
@tfprado Dude, i just comented the "$message->attach( Input::file('attachment') );" part, and uncommented the correct part, to make it the same as yours, and now it works!!!!!!!!!!!!!!!!! YOU ARE A LIFE SAVER MAN, THANK YOU VERY MUCH!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Kusdrae** [comment] 2021-06-24 13:27
@tfprado Hey, since you already helped me once (a lot), do you know if there's a way to make the form not accept duplicated data? Like, if i register someone in a form with the name "Test", is it possible to not allow any other form with the name "Test" ?

**Comment by tfprado** [comment] 2021-06-24 14:03
@Kusdrae I believe you can use any regular [Laravel validation](https://laravel.com/docs/8.x/validation#available-validation-rules) rules. You are looking for [Unique(database)](https://laravel.com/docs/8.x/validation#rule-unique). 
The plugin author has a lot of helpful documentation [here on his website](https://skydiver.github.io/october-plugin-forms/docs/validation/validation/)
Edit: It might be worth opening another question since we are no longer talking about uploads here

**Closed** 2022-06-14 04:57 UTC
Labels: question
