### ISSUE TITLE
Client's email as sender's email in the form

### ISSUE THREAD

**Issue by worldofsmarty** [skydiver/october-plugin-forms#66] opened 2017-06-13 09:54 UTC
Hey there,

Can we have clients email as sender's email while sending/submitting the form. This is something very important for our business and if you can reply as soon as possible then it will help me a lot.

Regards,
Vijay Patel

**Comment by skydiver** [comment] 2017-06-13 19:22
This is a duplicate of #60 
We are already working on this with the help of @Alex360hd

**Closed** 2017-06-13 19:22 UTC
Labels: duplicate
